apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cluster-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-cluster-operator
  template:
    metadata:
      labels:
        name: redis-cluster-operator
    spec:
      serviceAccountName: redis-cluster-operator
      containers:
        - name: redis-cluster-operator
          # Replace this with the built image name
          image: zrbcool/redis-cluster-operator:v0.0.1
          command:
          - redis-cluster-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "redis-cluster-operator"
